version: "3"

services:
#  mongo:
#    image: mongo
#    ports:
#      - '27017:27017'
#    environment:
#      MONGO_INITDB_DATABASE: bcn_data_service
#      MONGO_INITDB_ROOT_USERNAME: root
#      MONGO_INITDB_ROOT_PASSWORD: password
#    volumes:
#      - ./mongo/init/init.js:/docker-entrypoint-initdb.d/init.js
#
#  mongo-express:
#    image: mongo-express
#    restart: always
#    ports:
#      - '8081:8081'
#    environment:
#      ME_CONFIG_MONGODB_ADMINUSERNAME: root
#      ME_CONFIG_MONGODB_ADMINPASSWORD: password
#      ME_CONFIG_MONGODB_URL: mongodb://root:password@mongo:27017/

  dynamo:
    image: amazon/dynamodb-local
    ports:
      - '8000:8000'
#  azure:
#    image  : mcr.microsoft.com/azure-cli
#    command: ""
#    stdin_open: true
#    tty: true
#    volumes:
#      - ./azure-dist:/func-src
#  azurite:
#    image: mcr.microsoft.com/azure-storage/azurite
##    command: "azurite --blobHost 127.0.0.1 --blobPort 10000 --queueHost 127.0.0.1 --queuePort 10001"
#    ports:
#      - '10000:10000'
#      - '10001:10001'
#      - '10002:10002'