/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cloud_logic_custom": [
        {
            "name": "api",
            "endpoint": "https://ldwk46ls4a.execute-api.us-east-1.amazonaws.com/staging",
            "region": "us-east-1"
        }
    ],
    "aws_dynamodb_all_tables_region": "us-east-1",
    "aws_dynamodb_table_schemas": [
        {
            "tableName": "dynamo959558df-staging",
            "region": "us-east-1"
        },
        {
            "tableName": "users",
            "region": "us-east-1"
        },
        {
            "tableName": "activity",
            "region": "us-east-1"
        },
        {
            "tableName": "user_actions",
            "region": "us-east-1"
        }
    ]
};


export default awsmobile;
